// const apartments = [
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
//   {
//     name: "Diamond Manor Apartment",
//     img: "https://tunatheme.com/tf/html/quarter-preview/quarter/img/img-slide/31.jpg",
//     billPerMOnth: "34900",
//     description:
//       "Massa tempor nec feugiat nisl pretium.Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet.Neque volutpat ac tincidunt vitae semper quis lectus.Turpis in eu mi bibendum neque egestas congue quisque.Sed elementum tempus egestas sed sed risus pretium quam.Dear Dignissim sodales ut eu sem. Open up to the garden and use a separate laundry room. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi, dicta!",
//     owner: "Rosalina D. Willaimson",
//     area: "120 ",
//     rooms: "4",
//     bed: "3",
//     bath: "2",
//     built: "2014",
//     location: "Belmont Gardens, Chicago",
//   },
// ];
